### ISSUE TITLE
The "money" indicator does not update

### ISSUE THREAD

**Issue by HalconBM** [RedEM-RP/redem_roleplay#22] opened 2020-06-05 14:07 UTC
When you add money by command or simply any script that subtracts or adds an amount of money to the player it does not show it in the fixed money indicator
![Anotación 2020-06-05 160625](https://user-images.githubusercontent.com/53305213/83885436-a53cdc80-a746-11ea-9b40-efffb34bd050.png)

**Comment by kanersps** [comment] 2020-06-11 12:20
I’m afraid I’m unable to reproduce after testing. Anything specific that’s causing it?

**Comment by Gregorsaur** [comment] 2020-07-12 10:35
This is now fixed, please update RedEMRP

**Closed as completed** 2020-07-17 21:24 UTC
